# Generated by Django 4.0 on 2022-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookcopy_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maximum_retail_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
